function debugLog(...n){DEBUG_MODE&&console.log(...n)}function clockUpdateTime(n,t,i="Asia/Shanghai"){function u(n,t){return("0".repeat(t)+n).slice(-t)}function e(){const t=new Date,r={timeZone:i,hour12:!1},f=t.toLocaleString("en-US",r),n=new Date(f);document.getElementById("card-clock-time").innerHTML=u(n.getHours(),2)+":"+u(n.getMinutes(),2)+":"+u(n.getSeconds(),2);document.getElementById("card-clock-clockdate").innerHTML=`${n.getFullYear()}-${u(n.getMonth()+1,2)}-${u(n.getDate(),2)} ${o[n.getDay()]}`;document.getElementById("card-clock-dackorlight").innerHTML=n.getHours()>12?" P M":" A M"}const f=document.getElementById("hexo_electric_clock");if(f){let r="#000";switch(n.now.icon){case"100":r="#fdcc45";break;case"101":r="#fe6976";break;case"102":case"103":r="#fe7f5b";break;case"104":case"150":case"151":case"152":case"153":case"154":case"800":case"801":case"802":case"803":case"804":case"805":case"806":case"807":r="#2152d1";break;case"300":case"301":case"305":case"306":case"307":case"308":case"309":case"310":case"311":case"312":case"313":case"314":case"315":case"316":case"317":case"318":case"350":case"351":case"399":r="#49b1f5";break;case"302":case"303":case"304":r="#fdcc46";break;case"400":case"401":case"402":case"403":case"404":case"405":case"406":case"407":case"408":case"409":case"410":case"456":case"457":case"499":r="#a3c2dc";break;case"500":case"501":case"502":case"503":case"504":case"507":case"508":case"509":case"510":case"511":case"512":case"513":case"514":case"515":r="#97acba";break;case"900":case"999":r="red";break;case"901":r="#179fff"}f.innerHTML=`
    <div class="clock-row">
      <span id="card-clock-clockdate" class="card-clock-clockdate"></span>
      <span class="card-clock-weather"><i class="qi-${n.now.icon}-fill" style="color: ${r}"></i> ${n.now.text} <span>${n.now.temp}</span> ℃</span>
      <span class="card-clock-humidity">💧 ${n.now.humidity}%</span>
    </div>
    <div class="clock-row">
      <span id="card-clock-time" class="card-clock-time"></span>
    </div>
    <div class="clock-row">
      <span class="card-clock-windDir"> <i class="qi-gale"></i> ${n.now.windDir}</span>
      <span class="card-clock-location">${t}</span>
      <span id="card-clock-dackorlight" class="card-clock-dackorlight"></span>
    </div>
  `;const o=["SUN","MON","TUE","WED","THU","FRI","SAT"];setInterval(e,1e3);e()}}function getIpAndWeather(n=""){const t=n=>{debugLog("🔍 使用城市:",n);const t=`${qweather_api_host}/geo/v2/city/lookup?location=${encodeURIComponent(n)}&key=${qweather_key}`;fetch(t).then(n=>n.json()).then(t=>{const i=t.location?.[0];if(!i)throw new Error("未找到 location id");const r=i.id,u=i.tz||"Asia/Shanghai";debugLog("🔍 location id:",r,"🕐 时区:",u);const f=`${qweather_api_host}/v7/weather/now?location=${r}&key=${qweather_key}`;return fetch(f).then(n=>n.json()).then(t=>{debugLog("🔍 天气数据:",t),clockUpdateTime(t,n,u)})}).catch(n=>console.error("❌ 获取城市或天气错误:",n))};if(n&&n.trim()!=="")t(n);else{const n=`https://restapi.amap.com/v3/ip?key=${gaud_map_key}`;fetch(n).then(n=>n.json()).then(n=>{const i=n.city&&n.city!==""?n.city:n.province||"未知城市";t(i)}).catch(n=>console.error("❌ 高德IP接口错误:",n))}}const DEBUG_MODE=!1;getIpAndWeather(default_city)